#!/usr/bin/env node
/**
 * Creates or repairs the repo-root `.env` so a fresh clone runs with no manual
 * configuration.
 *
 * WHY THIS EXISTS
 * Three things previously had to be done by hand before anything would start:
 * copy `.env.example`, generate a JWT secret, and point `DATABASE_URL` at a
 * database that actually exists on the machine. Each is mechanical, and each
 * failed loudly-but-late (Prisma refusing to load, or the server exiting on a
 * Zod error). They are done here instead.
 *
 * Two of them are also a security matter, not just convenience:
 *
 *   - `.env.example` ships a placeholder JWT_SECRET that is 50 characters long,
 *     so it *passes* the `min(32)` validation. Copying the file verbatim would
 *     produce a working app whose session tokens are signed with a secret
 *     published in the repository. This script always replaces a placeholder
 *     with `randomBytes(48)`.
 *   - The same applies to TURN_SECRET, which mints TURN credentials.
 *
 * It is idempotent and conservative: a value that is already present and valid
 * is never touched, so it is safe to run on every `npm run dev`.
 *
 *   node scripts/ensure-env.mjs
 */
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const ENV_FILE = resolve(repoRoot, '.env');
const EXAMPLE_FILE = resolve(repoRoot, '.env.example');

/**
 * The database. SQLite needs no server, no credentials and no container, so
 * `git clone && npm install && npm run dev` works on a fresh machine — and it is
 * the same engine in production (see docs/database.md). Prisma resolves this
 * path relative to prisma/schema.prisma.
 */
const SQLITE_URL = 'file:./dev.db';

/** Secrets that appear in the repository and must never survive into a .env. */
const PLACEHOLDER_SECRETS = new Set([
  'change-me-to-a-long-random-string-at-least-32-chars',
  'changeme',
  'change-me',
  'your-secret-here',
  'secret',
]);

const generateSecret = (bytes) => randomBytes(bytes).toString('base64url');

function unquote(value) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }
  return value;
}

/** KEY=VALUE pairs, ignoring comments and blank lines. */
function parseEnv(text) {
  const entries = new Map();
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim().replace(/^export\s+/, '');
    entries.set(key, unquote(line.slice(eq + 1).trim()));
  }
  return entries;
}

/** Replaces KEY's line in place, preserving surrounding comments; appends if absent. */
function setKey(text, key, value) {
  const line = `${key}=${JSON.stringify(value)}`;
  const pattern = new RegExp(`^[ \\t]*(?:export[ \\t]+)?${key}[ \\t]*=.*$`, 'm');
  if (pattern.test(text)) return text.replace(pattern, line);
  return `${text.replace(/\s*$/, '')}\n${line}\n`;
}

const isUsableSecret = (value) =>
  typeof value === 'string' && value.length >= 32 && !PLACEHOLDER_SECRETS.has(value);

const HEADER = `# ---------------------------------------------------------------------------
# Generated by scripts/ensure-env.mjs on first run. Safe to edit by hand:
# existing values are never overwritten, only missing or placeholder ones are
# filled in. Delete this file to regenerate it from scratch.
#
# Secrets below were generated locally and are unique to this checkout.
# ---------------------------------------------------------------------------

`;

/** Builds a first-run .env from .env.example, with real secrets and a real database. */
function createFromExample() {
  if (!existsSync(EXAMPLE_FILE)) {
    // Only reachable if the template was deleted; every entry point still gets a
    // clear Zod error from env.ts naming the variables it needs.
    throw new Error(`.env.example is missing at ${EXAMPLE_FILE}; cannot bootstrap .env`);
  }
  // Drop the example's own banner ("Copy to .env and fill in"), which is an
  // instruction to the reader of the template and a lie inside the result.
  let text = readFileSync(EXAMPLE_FILE, 'utf8').replace(/^(?:[ \t]*#.*\r?\n)+/, '');

  text = setKey(text, 'JWT_SECRET', generateSecret(48));
  text = setKey(text, 'TURN_SECRET', generateSecret(32));
  text = setKey(text, 'DATABASE_URL', SQLITE_URL);

  return HEADER + text.replace(/^\s+/, '');
}

/**
 * Fills the gaps in an existing .env without disturbing anything that works.
 * Returns a list of human-readable changes.
 */
function repairExisting(text) {
  const changes = [];
  const current = parseEnv(text);
  const example = existsSync(EXAMPLE_FILE) ? parseEnv(readFileSync(EXAMPLE_FILE, 'utf8')) : new Map();

  if (!isUsableSecret(current.get('JWT_SECRET'))) {
    text = setKey(text, 'JWT_SECRET', generateSecret(48));
    changes.push(
      current.has('JWT_SECRET')
        ? 'replaced JWT_SECRET (was missing, too short, or the published placeholder)'
        : 'added a generated JWT_SECRET',
    );
  }

  // TURN_SECRET is only consulted when TURN_SERVER is set, so an empty value is
  // legitimate. Replace it only if it is a known placeholder pretending to be real.
  const turn = current.get('TURN_SECRET');
  if (turn && !isUsableSecret(turn)) {
    text = setKey(text, 'TURN_SECRET', generateSecret(32));
    changes.push('replaced a placeholder TURN_SECRET');
  }

  const dbUrl = current.get('DATABASE_URL');
  if (!dbUrl) {
    text = setKey(text, 'DATABASE_URL', SQLITE_URL);
    changes.push(`set DATABASE_URL to ${SQLITE_URL} (none was configured)`);
  } else if (!dbUrl.startsWith('file:')) {
    // Do not silently rewrite it — someone pointed this somewhere on purpose,
    // and env.ts will reject it at boot with the reason. Just say so early.
    changes.push(
      `WARNING: DATABASE_URL is "${dbUrl}" but Sonder uses SQLite; expected a file: path`,
    );
  }

  // Drop a variable that no longer exists, so an older .env does not look like
  // it is still configuring something.
  if (current.has('DEV_DATABASE_URL')) {
    text = text.replace(/^[ \t]*(?:export[ \t]+)?DEV_DATABASE_URL[ \t]*=.*\r?\n?/m, '');
    changes.push('removed DEV_DATABASE_URL (there is one database now)');
  }

  // Anything the example documents but this file predates. Keeps an old .env
  // working when a new knob is introduced, instead of failing Zod validation.
  const managed = new Set(['JWT_SECRET', 'TURN_SECRET', 'DATABASE_URL', 'DEV_DATABASE_URL']);
  const added = [];
  for (const [key, value] of example) {
    if (managed.has(key) || current.has(key)) continue;
    text = setKey(text, key, value);
    added.push(key);
  }
  if (added.length > 0) changes.push(`added missing key(s): ${added.join(', ')}`);

  return { text, changes };
}

export function ensureEnv({ quiet = false } = {}) {
  const say = (message) => {
    if (!quiet) console.log(`[ensure-env] ${message}`);
  };

  if (!existsSync(ENV_FILE)) {
    const text = createFromExample();
    writeFileSync(ENV_FILE, text, 'utf8');
    say(`created .env with a generated JWT_SECRET and DATABASE_URL=${SQLITE_URL}`);
    return { created: true, changes: [] };
  }

  const original = readFileSync(ENV_FILE, 'utf8');
  const { text, changes } = repairExisting(original);
  if (changes.length === 0) return { created: false, changes: [] };

  writeFileSync(ENV_FILE, text, 'utf8');
  for (const change of changes) say(change);
  return { created: false, changes };
}

/** Loads .env into process.env without overriding the real environment. */
export function loadEnvIntoProcess() {
  if (!existsSync(ENV_FILE)) return;
  for (const [key, value] of parseEnv(readFileSync(ENV_FILE, 'utf8'))) {
    if (process.env[key] === undefined) process.env[key] = value;
  }
}

const invokedDirectly =
  process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (invokedDirectly) {
  try {
    const result = ensureEnv();
    if (!result.created && result.changes.length === 0) {
      console.log('[ensure-env] .env is complete; nothing to do');
    }
  } catch (error) {
    console.error(`[ensure-env] ${error.message}`);
    process.exit(1);
  }
}
